# You would run this on the Kubernetes Raspberry Pi Control Plane
# Important: Run this first!

- name: Reset Fluent-bit
  hosts: localhost
  tasks:
    - name: Reset Fluent-bit
      command: helm uninstall -n "{{ namespace }}" elasticsearch
      delegate_to: localhost

    - name: Delete PVC 0
      command: kubectl delete pvc -n "{{ namespace }}" elasticsearch-master-elasticsearch-master-0

    - name: Delete PVC 1
      command: kubectl delete pvc -n "{{ namespace }}" elasticsearch-master-elasticsearch-master-1
