apiVersion: v1
kind: Namespace
metadata:
  name: "{{ namespace }}"
  labels:
    name: monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: monitoring
type: Opaque
data:
  username: {{ .Values.elasticsearch.username | b64enc }}
  password: {{ .Values.elasticsearch.password | b64enc }}
